version: 0.0
os: linux
hooks:
    ApplicationStop:
        - location: app_scripts/kill_container.sh
          timeout: 300
          runas: root
    ApplicationStart:
        - location: app_scripts/start_container.sh
          timeout: 300
          runas: root
